//! The command line, as a reusable type.
//!
//! [`Args`] and [`run`] are public on purpose: the `vidl` binary is nothing but
//! `run(Args::parse())`, so *anything* the binary can do is reachable from the library with the
//! same flags and the same behaviour. An embedder that wants `vidl`'s command line as part of
//! its own flattens [`Args`] into its parser rather than restating eleven flags that would then
//! drift.
//!
//! A caller that wants to make the routing decision itself skips both and drives
//! [`crate::classify`] plus the `download_*` functions with an [`Env`].

use std::path::PathBuf;

use clap::Args as ClapArgs;

use crate::{Env, Link, download_channel, download_generic, download_playlist, download_video, taglist};

/// Every option the `vidl` command line accepts. Mirrors [`Env`] one-for-one, plus the two
/// arguments that are the CLI's own business: what to download, and where to put it.
#[derive(ClapArgs, Clone, Debug, Default)]
pub struct Args {
    // Deliberately not `required_unless_present = "taglist"`: an embedder that flattens this
    // struct cannot widen a clap-level requirement to cover its own no-URL actions (a cookie
    // import, a site listing), so the check lives in `run` instead — see its test.
    /// A video URL — YouTube (video, playlist, or channel) or any other site yt-dlp supports
    pub url: Option<String>,
    /// Destination root — YouTube playlists/channels build folder trees here; other sites
    /// download into it directly
    #[arg(long, default_value = ".")]
    pub into: PathBuf,
    /// A YouTube video link that also names a playlist (`watch?v=…&list=…`) downloads the whole
    /// playlist by default; this takes just the video
    #[arg(long)]
    pub single: bool,
    /// A cookies file (Netscape format, as browser extensions export) — only needed for
    /// age-restricted content or networks that bot-wall; home connections rarely do
    #[arg(long)]
    pub cookies: Option<PathBuf>,
    /// Read cookies from an installed browser: `<browser>[:<profile-or-dir>]`, e.g. `firefox`
    #[arg(long, value_name = "SPEC")]
    pub cookies_from_browser: Option<String>,
    /// Audio only: extract the best audio track (kept as-is, no re-encode); on the YouTube
    /// path subtitles arrive as metadata tags (`subtitles_en`, `subtitles_he_autogenerated`, …)
    #[arg(long)]
    pub audio: bool,
    /// Cap the video height (e.g. 1080) — takes the best formats at or under it
    #[arg(long, value_name = "HEIGHT")]
    pub res: Option<u32>,
    /// Let yt-dlp use IPv6. IPv4 is forced by default — on a broken or slow IPv6 route, every
    /// request otherwise stalls ~5s on the fallback. Pass this on an IPv6-only network
    #[arg(long)]
    pub allow_ipv6: bool,
    /// Embed a cover-art thumbnail into each video (off by default — it costs extra requests).
    /// Handled as a late, idempotent pass: it skips videos that already have one and, ignoring
    /// the download archive, will patch previously-downloaded videos on a re-run
    #[arg(long)]
    pub thumbnail: bool,
    /// Force a subtitle scan of the target video(s) and embed any expected tracks that are
    /// missing. Subtitles already ride a normal download; this late, idempotent pass (ignoring
    /// the download archive) is for patching previously-downloaded videos on a re-run
    #[arg(long)]
    pub subtitles: bool,
    /// Print the notable yt-dlp flags (usable after `--`), then yt-dlp's full option list
    #[arg(short = 't', long)]
    pub taglist: bool,
    /// Anything after `--` is handed to yt-dlp verbatim, after our defaults — a repeated
    /// flag resolves in its favor; `-t` lists the ones worth knowing
    #[arg(last = true)]
    pub extra: Vec<String>,
}

impl Args {
    /// The download options these arguments describe, borrowed from `self`. Splitting this out
    /// lets a caller reuse the parsed flags while overriding one field — the usual reason being
    /// cookies it acquired some other way.
    pub fn env(&self) -> Env<'_> {
        Env {
            cookies: self.cookies.as_deref(),
            cookies_from_browser: self.cookies_from_browser.as_deref(),
            audio: self.audio,
            res: self.res,
            allow_ipv6: self.allow_ipv6,
            thumbnail: self.thumbnail,
            subtitles: self.subtitles,
            extra: &self.extra,
        }
    }
}

/// Do what the `vidl` command line says, and give back its exit code.
///
/// Creates the destination, works out what the URL points at, and hands off to the matching
/// `download_*`. `--taglist` prints the flag reference and stops without touching the network.
pub fn run(args: Args) -> i32 {
    if args.taglist {
        return taglist();
    }
    let Some(url) = args.url.clone() else {
        eprintln!("vidl: a URL is required (or --taglist for the flag reference)");
        return 2;
    };
    if let Err(err) = std::fs::create_dir_all(&args.into) {
        eprintln!("vidl: cannot create {}: {err}", args.into.display());
        return 1;
    }
    let env = args.env();
    match crate::classify(&url, args.single) {
        Link::Video => download_video(&url, &args.into, env),
        Link::Playlist { id } => download_playlist(&url, &id, &args.into, env),
        Link::Channel { root } => download_channel(&root, &args.into, env),
        Link::Generic => download_generic(&url, &args.into, env),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    #[derive(Parser)]
    struct Cli {
        #[command(flatten)]
        args: Args,
    }

    fn parse(argv: &[&str]) -> Args {
        Cli::parse_from(std::iter::once("vidl").chain(argv.iter().copied())).args
    }

    #[test]
    fn the_parsed_flags_reach_the_env_unchanged() {
        let args = parse(&["u", "--audio", "--res", "720", "--subtitles", "--", "-q"]);
        let env = args.env();
        assert!(env.audio);
        assert_eq!(env.res, Some(720));
        assert!(env.subtitles);
        assert_eq!(env.extra, ["-q"], "everything after `--` is yt-dlp's, verbatim");
        assert!(!env.thumbnail, "an unmentioned flag stays off");
    }

    #[test]
    fn a_missing_url_is_refused_by_run_not_by_the_parser() {
        // The parser stays permissive so an embedder can add its own no-URL actions (a cookie
        // import, a compatibility listing) without fighting a `required_unless_present` it
        // cannot extend through `#[command(flatten)]`.
        assert!(Cli::try_parse_from(["vidl"]).is_ok(), "the parser allows it");
        assert_eq!(run(parse(&[])), 2, "`run` is what refuses, and says so");
        assert_eq!(parse(&["https://x/v"]).url.as_deref(), Some("https://x/v"));
    }

    #[test]
    fn cookies_reach_the_env_by_either_route() {
        assert_eq!(parse(&["u", "--cookies", "/c.txt"]).env().cookies.unwrap().to_str(), Some("/c.txt"));
        assert_eq!(parse(&["u", "--cookies-from-browser", "firefox:/d"]).env().cookies_from_browser, Some("firefox:/d"));
    }

    #[test]
    fn an_embedder_can_override_one_field_and_keep_the_rest() {
        // The reason `env()` is public: an embedder parses the same flags, then substitutes
        // cookies it acquired itself. Nothing else about the parsed arguments should shift.
        let args = parse(&["u", "--audio", "--res", "480"]);
        let mut env = args.env();
        env.cookies_from_browser = Some("firefox:/imported");
        assert_eq!(env.cookies_from_browser, Some("firefox:/imported"));
        assert!(env.audio);
        assert_eq!(env.res, Some(480));
    }

    #[test]
    fn the_destination_defaults_to_here() {
        assert_eq!(parse(&["u"]).into, PathBuf::from("."));
        assert_eq!(parse(&["u", "--into", "/tmp/v"]).into, PathBuf::from("/tmp/v"));
    }
}
